### ISSUE TITLE
Install constants on windows 10

### ISSUE THREAD

**Issue by JanaPitanga** [3kwa/constants#2]
Is it possible to import this library into windows with conda?

When I try:

    import constants

I have this error:

    ModuleNotFoundError: No module named 'constants'

And when I try:

    from . import constants

I have this error:

    ImportError: cannot import name 'constants'

I tried to install with the conda, but it does not seem to work on windows:

    conda install -c auto constants

Is it possible to install on windows?

Thanks!

**Comment by 3kwa** [comment]
constants predate the existence of conda

You can't conda install constants but you can pip install constants in a conda environment (I do often)

**Comment by JanaPitanga** [comment]
It works! Thanks!
