### ISSUE TITLE
'cannot install module Constants'

### ISSUE THREAD

**Issue by datatalking** [3kwa/constants#3]
When I tried to install constants it kept telling me that it could not install it, when I tried in VScode, pycharm and sublime I got the same error.

Then when I went to terminal to install via 'pip install constants' it installs just fine but none of my IDE can find the package.

Is this configured some how or how can I access constants?

Can I help contribute to the your code?

<img width="1150" alt="Screen Shot 2022-10-17 at 12 00 01 PM" src="https://user-images.githubusercontent.com/11813209/196262388-720996a8-92cf-43eb-86b4-3db2e15404c4.png">

**Comment by datatalking** [comment]
With further research I'm finding that the package is only spec'd for python 3.3 and lower, what would we need to do to update it to python 3.7, or 3.9?

**Comment by 3kwa** [comment]
Thanks Andrew - good catch - I completely forgot about the Python version spec - will fix!

**Comment by datatalking** [comment]
Hi Eugene,

Can you show me what this is and allow me to do this as my first contribution?

**Comment by 3kwa** [comment]
Sure thing Andrew - so the Python version spec is in setup.py and we probably would want to test > 3.3 using tox (tox.ini) - have a crack and let me know how you go.

**Comment by datatalking** [comment]
Ok so I think I'm making progress, found `tox.ini`, ran it to find a few things. Am I correct in adding or how should we address the following?

1. setup.py is missing dependencies so I added them in `setup.py` under install_requires=['tox', 'distutils', 'distutils.core', 'pytest'],
2. In`tox.ini` under [tox] i appended envlist to include 34, 35, 36 and 37.
3. added pytest from `deps=pytest` in tox to `setup.py` in install_requires=['tox', 'distutils', 'distutils.core', 'pytest'],
4. the output from `test_constants.py` shows 
'''

============================= test session starts ==============================
collecting ... collected 8 items

test_constants.py::TestConstants::test_boolean PASSED                    [ 12%]
test_constants.py::TestConstants::test_expression PASSED                 [ 25%]
test_constants.py::TestConstants::test_float_cast PASSED                 [ 37%]
test_constants.py::TestConstants::test_float_cast_starting_with_0 PASSED [ 50%]
test_constants.py::TestConstants::test_integer_cast PASSED               [ 62%]
test_constants.py::TestConstants::test_integer_with_leading_zero_not_cast PASSED [ 75%]
test_constants.py::TestConstants::test_invalid_expression PASSED         [ 87%]
test_constants.py::TestConstants::test_string_cast PASSED                [100%]

============================== 8 passed in 0.07s ===============================

Process finished with exit code 0
'''
5. the output from README.rst shows 
'''
============================= test session starts ==============================
collecting ... collected 8 items

test_constants.py::TestConstants::test_boolean PASSED                    [ 12%]
test_constants.py::TestConstants::test_expression PASSED                 [ 25%]
test_constants.py::TestConstants::test_float_cast PASSED                 [ 37%]
test_constants.py::TestConstants::test_float_cast_starting_with_0 PASSED [ 50%]
test_constants.py::TestConstants::test_integer_cast PASSED               [ 62%]
test_constants.py::TestConstants::test_integer_with_leading_zero_not_cast PASSED [ 75%]
test_constants.py::TestConstants::test_invalid_expression 
test_constants.py::TestConstants::test_string_cast 

============================== 8 passed in 0.03s ===============================

README.rst:0 ([doctest] README.rst)
113 raise an exception when an attempt is made to *change a constant*, ``constants``
114 issues warnings_ ...
115 
116 >>> import warnings
117 
118 >>> with warnings.catch_warnings(record=True) as warning:
119 ...     # reassigning the constant all
120 ...     consts.all = 2
121 
122 >>> warning[0].message
Expected:
    UserWarning('all changed to 2',)
Got:
    UserWarning('all changed to 2')
'''

This is getting quite involved but I'm not sure on the next step, I can send a PR and we can review it?

**Comment by datatalking** [comment]
Also found that upon running from terminal ' python setup.py install' I get an error that 'https://pypi.org/simple/warnings/'
'''
No local packages or working download links found for warnings
error: Could not find suitable distribution for Requirement.parse('warnings')
'''
Which makes sense that its built in so per https://stackoverflow.com/questions/47722353/how-to-install-warnings-package-in-python should I just nix references to it or?

**Comment by datatalking** [comment]
I updated the formatting of my longer post, should be more readable now.

**Comment by hav-sav2008** [comment]
@datatalking I'm currently doing the same algorithmic trading course as you and I too am having problems with import constants.defs, I have found that import constants works fine but as soon as I try import constants.defs a No module error pops up. If anyone can as stated before upgrade this package to work in python 3.6 or higher it would be much appreciated thank you.

**Comment by hav-sav2008** [comment]
Hi I'm still having an issue with `import constants.defs as defs` I've switched from Python Version 3.11 to 3.7 in hopes of it working but still I get the `ModuleNotFoundError: No module named 'constants.defs'; 'constants' is not a package` error, I'm not sure what's wrong or how to fix it but any help would be greatly appreciated thank you.

**Comment by hav-sav2008** [comment]
Update I used `from Exploration.constants.defs (add your def variables here)` and it worked completely fine

**Comment by 3kwa** [comment]
pushed a new version to PyPI using CalVer for versioning today - Python 2.6 to 3.11
